# Generated by Django 5.2.6 on 2025-11-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_composition'),
    ]

    operations = [
    ]
