# Generated by Django 5.2.8 on 2025-11-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20251105_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('pants', 'Pants'), ('coats', 'Coats'), ('skirts', 'Skirts'), ('tops', 'Tops'), ('dresses', 'Dress'), ('kids', 'Kids Wears'), ('homedecors', 'Home Decors'), ('bags', 'Bags'), ('footwears', 'Footwears'), ('pillars', 'Pillars'), ('toys', 'Toys'), ('jewellery', 'Jewellery'), ('baby', 'Baby Essentials')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default='Unknown'),
            preserve_default=False,
        ),
    ]
